# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  bookify-api:
    build:
      context: "D:\\MyProjects\\RiderProjects\\Bookify"
      dockerfile: "Src\\Bookify.Api\\Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Bookify.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bookify-api-local:dev"
    ports: []
    volumes:
    - "C:\\Users\\Notebook\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\MyProjects\\RiderProjects\\Bookify\\Src\\Bookify.Api:/app:rw"
    - "D:\\MyProjects\\RiderProjects\\Bookify:/src:rw"
    working_dir: "/app"
